server: 
  port: 9002
spring:
#项目名
  application:  
    name: school-user #指定服务名
#    数据库连接
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=UTF8
    username: root
    password: jiang
#    jpa数据操作
  jpa: 
    database: MySQL
    show-sql: true
#    redis缓存
  redis:
    host: 127.0.0.1
  resources:
    static-locations: classpath:/templates/
#    邮箱
  mail:
    host: smtp.qq.com 	#邮箱服务器地址
    username: 1786678583@qq.com  #邮箱账号
    password: ihypidhglruvbigd	#邮箱密码
    default-encoding: utf-8	#默认编码
#  mail:
#    host: smtp.163.com 	#邮箱服务器地址
#    username: siknight666@163.com  #邮箱账号
#    password: merryhappy123456	#邮箱密码
#    default-encoding: utf-8	#默认编码
#    token生成
jwt:
  config:
    key: school
    ttl: 3600000
#  36000000  十个小时过期
#3600000 = 一个小时 默认是毫秒 1秒=1000毫秒  ==>一个小时是 1*60分钟*60秒*1000毫秒=3600 000
#一分钟的话是 60*1000=60 000毫秒
#    ihypidhglruvbigd

