server: 
  port: 9001
spring:
#项目名
  application:  
    name: school-user #指定服务名
#    数据库连接
  datasource:  
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/school?characterEncoding=UTF8
    username: root
    password: jiang
#    jpa数据操作
  jpa: 
    database: MySQL
    show-sql: true
#    redis缓存
  redis:
    host: 127.0.0.1
#    消息队列
  rabbitmq:
    host: 127.0.0.1
#    邮箱
  mail:
    host: smtp.qq.com 	#邮箱服务器地址
    username: 1786678583@qq.com  #邮箱账号
    password: otqmibn	#邮箱密码
    default-encoding: utf-8	#默认编码
#    token生成
jwt:
  config:
    key: school
    ttl: 3600000
